//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Button module using socket 7 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        /// <summary>The Extender module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Extender extender;
        
        /// <summary>The Multicolor LED module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MulticolorLED ledLeft;
        
        /// <summary>The Multicolor LED module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MulticolorLED ledRight;
        
        /// <summary>The USB Host module using socket 1 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.USBHost usbHost;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZCerberus Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZCerberus)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZCerberus();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.button = new GTM.GHIElectronics.Button(7);
            this.extender = new GTM.GHIElectronics.Extender(4);
            this.ledLeft = new GTM.GHIElectronics.MulticolorLED(3);
            this.ledRight = new GTM.GHIElectronics.MulticolorLED(2);
            this.usbHost = new GTM.GHIElectronics.USBHost(1);
        }
    }
}
